#!/bin/sh

urlregex="(((http|https|gopher|gemini|ftp|ftps|git|file)://|www\\.)[a-zA-Z0-9.]*[:;a-zA-Z0-9./+@$&%?$\#=_~-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)"

urls="$(sed 's/.*│//g' | tr -d '\n' | # First remove linebreaks and mutt sidebars:
	grep -aEo "$urlregex" | # grep only urls as defined above.
	uniq | # Ignore neighboring duplicates.
	sed "s/\(\.\|,\|;\|\!\\|\?\)$//;
	s/^www./http:\/\/www\./")" # xdg-open will not detect url without http

[ -z "$urls" ] && exit 1

while getopts "hoc" o; do case "${o}" in
	h) printf "Optional arguments for custom use:\\n  -c: copy\\n  -o: xdg-open\\n  -h: Show this message\\n" && exit 1 ;;
	# o) chosen="$(echo "$urls" | dmenu -i  -fn 'JetBrains Mono:size=11'  -nb '#000000' -nf '#FFFFFF' -sb '#FFFFFF' -sf '#000000' -b -p 'Follow which url?' -l 10 )"
	# o) chosen="$(echo "$urls" | dmenu -i  -fn 'Dejavu Sans Book:size=11' -nb '#000000' -nf '#999999' -sb '#000000' -sf '#FFFFFF' -b -p 'Follow which url?' -l 10 )"
	o) chosen="$(echo "$urls" | dmenu -i  -fn 'Iosevka Comfy:size=12:antialias=true:autohint=true:style=SemiBold' -nb '#001F00' -nf '#999999' -sb '#004400' -sf '#FFFFFF' -p 'Follow which url? ↘' -l 10 )"
	setsid xdg-open "$chosen" >/dev/null 2>&1 & ;;
	c) echo "$urls" | dmenu -i -p 'Copy which url?' -l 10 | tr -d '\n' | xclip -selection clipboard ;;
	*) printf "Invalid option: -%s\\n" "$OPTARG" && exit 1 ;;
esac done
